[project]
name = "ab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
    "peft>=0.16.0",
    "streamlit>=1.46.1",
    "torch>=2.7.1",
]
